---
- name: Set add sample-central-services key to authorized keys.
  ansible.posix.authorized_key:
    ansible.builtin.user: ec2-user
    state: present
    key: "{{ lookup('file', '/home/ec2-user/.ssh/sample-central-services.key.pub') }}"
