- name: Verify aws directory exists
  file:
    path: "/home/{{ ansible_user }}/.aws"
    state: directory
  become: false

- name: Copy values file
  template:
    src: "aws_config.j2"
    dest: "/home/{{ ansible_user }}/.aws/config"