---
- name: Install boto3
  pip:
    name: boto3

- name: Install botocore
  pip:
    name: botocore

- name: Install aws ansible plugin
  command: ansible-galaxy collection install amazon.aws

- name: Install aws ansible plugin
  command: ansible-galaxy collection install community.docker