---
- name: Install boto3
  ansible.builtin.pip:
    name: boto3

- name: Install botocore
  ansible.builtin.pip:
    name: botocore

- name: Install aws ansible plugin
  ansible.builtin.command: ansible-galaxy collection install amazon.aws

- name: Install aws ansible plugin
  ansible.builtin.command: ansible-galaxy collection install community.docker