---
- name: Install FIPS.
  hosts: cp
  become: true
  become_user: root
  tasks:
    - name: Install fips.
      ansible.builtin.include_role:
        name: kubernetes_preinstall_configs
        tasks_from: fips.yml
