---
- name: Get kubeconfig.
  hosts: cp
  become: true
  become_user: root
  tasks:
    - name: Get kubeconfig.
      ansible.builtin.include_role:
        name: kubernetes-install
        tasks_from: get_kubeconfig.yml
