---
- name: Install firewalld.
  hosts: cp
  become: true
  become_user: root
  tasks:
    - name: Install firewalld.
      ansible.builtin.include_role:
        name: kubernetes-install
        tasks_from: firewalld.yml
