---
# tasks file for kubernetes-install-cleanup
- name: Clean up Install Files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  become: true
  loop: "{{ cleanup_kubernetes_files }}"

- name: EXPORT KUBECONFIG to bashrc
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: 'export KUBECONFIG=/etc/kubernetes/admin.conf'
    state: present

- name: EXPORT local/bin PATH to bashrc
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: 'export PATH="/usr/local/bin:$PATH"'
    state: present


- name: Reboot to finalize changes.
  ansible.builtin.reboot: